---
  server:
    port: 8080


  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/my-task-tracker
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver
